name: Go

on:
  push:
    branches: [ "master" ]
    # Pattern matched against refs/tags
    tags:        
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
      submodules: true

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        mkdir -p ./build/bin
        go build -v -o ./build/bin/go-orphan-tracker .

    - name: Test
      run: go test -v ./...
    
    - name: Upload release assets
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        files: ./build/bin/go-orphan-tracker
