name: Go

on:
  push:
    branches: [ "master" ]
    # Pattern matched against refs/tags
    tags:        
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        mkdir -p ./build/bin
        go build -v -o ./build/bin/go-orphan-tracker .

    - name: Test
      run: go test -v ./...
    
    - name: Upload to Release Action
      if: startsWith(github.ref, 'refs/tags/v')
      # You may pin to the exact commit or the version.
      # uses: Shopify/upload-to-release@9942a4c936dab172f7101dcc7dc20528ea949102
      uses: Shopify/upload-to-release@v1.0.1
      with:
        # Artifact name
        name: go-orphan-tracker
        # Path to the file to upload
        path: ./build/bin/go-orphan-tracker
        # Content type for the file
        # content-type: # optional, default is application/octet-stream
        # secrets.GITHUB_TOKEN
        repo-token: secrets.GITHUB_TOKEN
      
